group: common
fields:
  - identifier: amount
    type: Number
    properties:
      defaultValue: 0
      maximum: 100
      requied:  true
  - identifier: icon
    type: Icon
    properties:
      allowedExtensions: 'svg'
      minItems: 1
      maxItems: 1
      requied:  true
  - identifier: text
    type: Text
