group: common
fields:
  - identifier: slides
    type: Collection
    properties:
      allowAdd: true
      allowMove: true
      allowDelete: true
      minItems: 1
      maxItems: 5
      requied:  true
      fields:
        - identifier: image
          type: Image
          properties:
            minItems: 1
            maxItems: 1
            requied:  true
        - identifier: headline
          type: Text
        - identifier: text
          type: TextMultiline
        - identifier: buttonCaption
          type: Text
          properties:
            required: true
        - identifier: buttonLink
            type: Link
            properties:
              linkTypes: [page, external]
  - identifier: autoplay
    type: Toggle
    defaultValue: true
